# Generated by Django 3.0.7 on 2020-06-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='Summary',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
